package com.Kargo.Self_Ex_Genrator_Script;

public class Constants 
{
	public static final String ad_tag_url="https://storage.cloud.kargo.com/ad/network/tag/v3/_jK-jpqWVzw1IWgPtcqKQ0b.js";
	public static final String ad_Slot_ID="_jK-jpqWWqQ";
	public static final String Crative_Snippet="<div class=\"celtra-ad-v3\">\n    <!-- externalCreativeId  = raw %ecid! -->\n    <!-- externalPlacementId = raw %epid! -->\n    <!-- externalSiteId      = raw %esid! -->\n    <!-- externalLineItemId  = raw %eaid! -->\n    <img src=\"data:image/png,celtra\" style=\"display: none\" onerror=\"\n        (function(img) {\n            var params = {'placementId':'dcf0f454','clickUrl':'https://tk.kargo.com/t/cp.bFqt.1NzBI6niAI0?rand=%%CACHEBUSTER%%&kid=%%PATTERN:kid%%&kuid=%%PATTERN:kuid%%&url=%%CLICK_URL_UNESC%%','expandDirection':'up','preferredClickThroughWindow':'','clickEvent':'advertiser','externalAdServer':'DFPPremium','tagVersion':'3'};\n            [].slice.apply(img.parentNode.childNodes).forEach(function(n) { var decfs = { urldecode: decodeURIComponent, htmldecode: function(v) { var d = document.createElement('div'); d.innerHTML = v; return d.textContent; }, eval: function(v) { return eval(v); }, raw: function(v) { return v; } }; var m; if (n.nodeType == 8 &amp;&amp; (m = n.textContent.match(/^&#92;s+([&#92;w.]+)(&#92;[.+&#92;])?&#92;s+=&#92;s+(&#92;w+)&#92;s+(.*)$/i))) { try { params[m[1]+(m[2] || '')] = decfs[m[3]](m[4].replace(/^&#92;s+|&#92;s+$/g, '')); } catch (e) {} } });\n            var req = document.createElement('script');\n            req.id = params.scriptId = 'celtra-script-' + (window.celtraScriptIndex = (window.celtraScriptIndex||0)+1);\n            params.clientTimestamp = new Date/1000;\n            params.clientTimeZoneOffsetInMinutes = new Date().getTimezoneOffset();\n            var src = (window.location.protocol == 'https:' ? 'https' : 'http') + '://ads.celtra.com/6c4e2e89/web.js?';\n            for (var k in params) {\n                src += '&amp;' + encodeURIComponent(k) + '=' + encodeURIComponent(params[k]);\n            }\n            req.src = src;\n            img.parentNode.insertBefore(req, img.nextSibling);\n        })(this);\n    \"/>\n</div>";
	

}
